### PR TITLE
Migration : Jekyll to Hugo

### PR DESCRIPTION
**Pull request by napuzba**

### CODE REVIEW

**Comment by ribtoks** [comment]
I can see you removed file `README.md`. I requested on Upwork to add instructions how to run locally so I could verify. I know I can google how to run Hugo website locally, but it is much more convenient to have these instructions in the repository.

**Comment by napuzba** [comment]
You can run local server by invoking at project root:

    $ hugo server

The site will be available at [http://localhost:1313](http://localhost:1313/)

**Comment by ribtoks** [comment]
Great, so please include these instructions in `README.md` as was requested in the Upwork job description

**Comment by ribtoks** [comment]
Also, a question: did you try running the website? It has many differences or totally missing places if you compare with the original one. You can find couple of them on screenshots in this post. Please check all kinds of webpages in [Xpiks website](https://xpiksapp.com) and make sure they are exactly the same in new Hugo port.


Screen Shot 2019-10-05 at 11 16 19
Screen Shot 2019-10-05 at 11 20 32
Screen Shot 2019-10-05 at 11 21 46

**Comment by ribtoks** [comment]
Also in your PR: ruby binaries in `vendor/` are no longer needed since website will not use ruby anymore

**Comment by napuzba** [comment]
Please accept the PR and I will fix those issues

**Comment by ribtoks** [comment]
I'm sorry, but why do you need the PR to be accepted to fix the issues? Please fix them in your branch and send update to this PR. Thank you

**Comment by napuzba** [comment]
> Please fix them in your branch and send update to this PR. Thank you

Fixed all issues
- - -
> Screen Shot 2019-10-05 at 11 16 19

Fixed
- - -
> Screen Shot 2019-10-05 at 11 20 32

Fixed
- - -
> Screen Shot 2019-10-05 at 11 21 46

Works at my side (display google groups forum as expected)
- - -
> vendor/ are no longer needed since website will not use ruby anymore

The vendor/ is not part of this PR.
- - -
> include these instructions in README.md 

Add README.md  with basic instructions how to run locally.
- - -

**Comment by ribtoks** [comment]
I checked the website and there are multiple misalignments.

Screen Shot 2019-10-07 at 07 46 47
Screen Shot 2019-10-07 at 07 47 53
Screen Shot 2019-10-07 at 07 49 03
Screen Shot 2019-10-07 at 07 49 59
Screen Shot 2019-10-07 at 07 50 52

I didn't check all pages. Even the most topmost have those misalignments. You must check ALL pages and make sure they are the same as the original Jekyll website. "Definition of done" of this task is that new website looks exactly the same as the original one.

**Comment by ribtoks** [comment]
You did not fix all the errors I found and presented on screenshots!

FAQ page still has weird empty space (see hhttps://xpiksapp.com/faq/) and each tutorial page has much less vertical spaces than on the official website!

Screen Shot 2019-10-07 at 07 49 03
Screen Shot 2019-10-07 at 07 49 59

**Comment by ribtoks** [comment]
There're more differences:

1.
Here's status page: Date format is different (too verbose) from the main website.
image

2.
If you open website in mobile layout, styles of tutorials are somehow broken - current page is not selected anymore (Getting Started page)
image

**Comment by napuzba** [comment]
> Date format is different (too verbose) from the main website.
Fixed
- - -
> Current page is not selected anymore (Getting Started page)
Fix topic is selected and highlighted in 
- - -
>  open http://localhost:1313/tutorials/ and click on "Getting started" link in the main view ... On the official website "Getting started" section is highlighted 

This is the behavior of the official website as well.

Only when you you open topic page (For example /getting-started , /interface ) - you get this behavior.
- - -

**Pull request merged**
